server:
  port: 8989

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: report

  application:
    name: REPORT-SERVICE

  zipkin:
    base-url: http://localhost:9411/
